import Category from "./category.model.js";
import Tenant from "./main/tenant.model.js"
import District from "./main/district.model.js";
import Permission from "./permission.model.js";
import Product from "./product.model.js";
import Role from "./role.model.js";
import RolePermissions from "./rolePermissions.joinModel.js";
import State from "./main/state.model.js";
import User from "./user.model.js";
import UserRoles from "./userRoles.joinModel.js";
import NodeBatch from "./nodeBatch.model.js";
import TenantsName from "./main/tenantsName.model.js";
import Requisition from "./requisition.model.js";
import RequisitionItem from "./requisitionItem.model.js";
import HSN from "./hsn_master.model.js";
import Quotation from "./quotation.model.js";
import QuotationItem from "./quotationItem.model.js";
import PurchasOrder from "./purchasOrder.model.js";
import PurchaseOrderItem from "./purchaseOrderItem.model.js";
import Invoice from "./invoice.model.js";
import InvoiceItems from "./invoiceItems.model.js";
import BillOfMaterial from "./billOfMaterial.model.js";
import Brand from "./brand.model.js";
import UnitType from "./unitType.model.js";
import CategoryProducts from "./categoryProduct.joinModel.js";
import BrandProducts from "./brandProduct.joinModel.js";
import TenantBusinessFlowMaster from "./main/tenantBusinessFlowMaster.model.js";
import TenantBusinessFlow from "./businessModels/tenantBusinessFlow.model.js";
import BusinessNode from "./businessModels/businessNode.model.js";
import PackageType from "./packageType.model.js";
import NodeUser from "./nodeUsers.join_Model.js";
import NodeDetails from "./businessModels/nodeDetails.model.js";
import BusinessNodeType from "./businessModels/businessNodeType.model.js";
import RequisitionSupplier from "./requisitionSupplier.joinModel.js";
import NodeStockLedger from "./nodeStockLedger.model.js";
import GRN from "./grn.model.js";
import GRNItem from "./grnItems.model.js";
import RequisitionCategory from "./requisitionCategory.model.js";
import ManufacturingUnit from "./manufacturingUnit.model.js";
import RFQ from "./main/rfq.model.js";
import RFQItem from "./main/rfqItem.model.js";
import RfqQuotationItem from "./main/rfqQuotationItems.model.js";
import RfqQuotation from "./main/rfqQuotation.model.js";
import RfqQuotationRevision from "./main/RfqQuotationRevisions .model.js";
import BlanketOrder from "./main/blanketOrder.model.js";
import BlanketOrderItem from "./main/BlanketOrderItems.model.js";
import NodeBatchItems from "./nodeBatchItems.model.js";
import NodeStockLedgerItem from "./nodeStockLedgerItem.model.js";
import Vendor from "./vendor.model.js";
import SalesOrder from "./salesOrder.model.js";
import SalesOrderItem from "./salesOrderItem.model.js";
import BpoIndent from "./main/BpoIndent.model.js";
import BpoIndentItem from "./main/BpoIndentItem.model.js";

const defineRootModels = (rootSequelize) => {
    Tenant(rootSequelize);
    District(rootSequelize);
    State(rootSequelize);
    Permission(rootSequelize);
    Role(rootSequelize);
    RolePermissions(rootSequelize);
    UserRoles(rootSequelize);
    TenantsName(rootSequelize);
    User(rootSequelize);
    BusinessNodeType(rootSequelize);
    TenantBusinessFlowMaster(rootSequelize);
    RfqQuotation(rootSequelize);
    RfqQuotationRevision(rootSequelize);
    RfqQuotationItem(rootSequelize);
    RFQ(rootSequelize);
    RFQItem(rootSequelize);
    BlanketOrder(rootSequelize);
    BlanketOrderItem(rootSequelize);
    BpoIndent(rootSequelize);
    BpoIndentItem(rootSequelize);

    return rootSequelize.models;
}

const defineTenantModels = (sequelize) => {
    Category(sequelize);
    Permission(sequelize);
    Product(sequelize);
    Role(sequelize);
    RolePermissions(sequelize);
    User(sequelize);
    UserRoles(sequelize);
    Requisition(sequelize);
    RequisitionItem(sequelize);
    HSN(sequelize);
    Quotation(sequelize);
    QuotationItem(sequelize);
    PurchasOrder(sequelize);
    PurchaseOrderItem(sequelize);
    Invoice(sequelize);
    InvoiceItems(sequelize);
    BillOfMaterial(sequelize);
    Brand(sequelize);
    UnitType(sequelize);
    Vendor(sequelize);
    CategoryProducts(sequelize);
    BrandProducts(sequelize);
    BusinessNodeType(sequelize);
    TenantBusinessFlow(sequelize);
    BusinessNode(sequelize);
    PackageType(sequelize);
    NodeUser(sequelize);
    NodeDetails(sequelize);
    RequisitionSupplier(sequelize);
    NodeStockLedger(sequelize);
    NodeBatch(sequelize);
    NodeBatchItems(sequelize);
    NodeStockLedgerItem(sequelize);
    GRN(sequelize);
    GRNItem(sequelize);
    RequisitionCategory(sequelize);
    ManufacturingUnit(sequelize);
    SalesOrder(sequelize);
    SalesOrderItem(sequelize);

    return sequelize.models;
}

export { defineTenantModels, defineRootModels };